server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.99.100:3306/test
        username: root
        password: admins
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      database: 0
      host: 192.168.99.100
      port: 6379
      password: Zww123456
      timeout: 0
      pool: 
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zww.mybatis.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
#多redis连接配置 
#spring.redis.shard.2.host = 127.0.0.1  
#spring.redis.shard.2.password =   
#spring.redis.shard.2.port = 6379  

    